### ISSUE TITLE
Pitfalls when running on Debian

### ISSUE THREAD

**Issue by mirabilos** [tomato42/ecpp-verifier#46]
It would be kind to add this to the documentation:

----

You can install all prerequisites from the repository, no need for `pip3` or to compile anything:

    sudo apt-get install python3-gmpy2 python3-ecdsa

However, you cannot run the file directly as its shebang points to Python 2, which you probably don’t have installed any more. So use…

    PYTHONPATH=src python3 ./ecpp --help

… etc. (that is, put a `python3` before the script name).

**Comment by mirabilos** [comment]
Hm. Maybe even add a “run-in-repo” wrapper?

```
cat >run.sh <<\EOF
#!/bin/sh
set -ex
basedir=$(cd "$(dirname "$0")" && pwd)
PYTHONPATH=$basedir/src
export PYTHONPATH
exec python3 "$basedir/ecpp" "$@"
EOF
chmod +x run.sh
```

**Comment by mirabilos** [comment]
The `parallel` command from the README also does not work. I had to use this (4-core CPU with disabled HT):

    export PYTHONPATH=$PWD/src
    parallel -j5 -i sh -c "echo {} && ecpp -i {}" -- in/*.out

I assume this is because parallel(1) is from `moreutils`, not GNU parallel.

**Comment by tomato42** [comment]
1. Actually if you are running Python 2, you're running some really Long Term Support distribution, like RHEL-6/CentOS 6, so those should be in minority; probably switching the python scripts to refer to python3 isn't a bad idea (possibly with a note for how to use `python2`).
2. I'm not sure about usefulness of a run-in-repo wrapper; if you're installing dependencies anyway, you might as well just install the repo itself...
3. `parallel` needs to be the GNU one, yes. But I see that there is a note in README already that says that, not sure what we could do more to make it clear. It's not an action that regular users need to perform... (90% the reason it's there, is so that I remember what command to use to verify the primality certificates before I merge them)

**Comment by mirabilos** [comment]
Hubert Kario dixit:

>1. Actually if you are running Python 2, you're running some really
>Long Term Support distribution, like RHEL-6/CentOS 6, so those should
>be in minority; probably switching the python scripts to refer to
>python3 isn't a bad idea (possibly with a note for how to use
>`python2`).

I’m not running Python 2 ;-)

***@***.***:~ $ python
/bin/mksh: python: inaccessible or not found

I’m running py3k but it must be called as “python3”.

>2. I'm not sure about usefulness of a run-in-repo wrapper; if you're
>installing dependencies anyway, you might as well just install the repo
>itself...

No, I’m installing the dependencies via the package manager. I’m an
absolute enemy of constructs like pip, npm etc. so I’m not going to
use them. All dependencies are available as proper Debian packages,
so I’m not going to install *anything*, so a run-from-repo wrapper
would be the standard way to go.

>3. `parallel` needs to be the GNU one, yes. But I see that there is a
>note in README already that says that, not sure what we could do more
>to make it clear. It's not an action that regular users need to
>perform... (90% the reason it's there, is so that I remember what
>command to use to verify the primality certificates before I merge
>them)

OK. But I apparently found an equivalent invocation for moreutils
parallel. Maybe you can just include both, so the user will know?
“man parallel” for moreutils starts with…

PARALLEL(1)                        moreutils                       PARALLEL(1)

… so this is how the user can distinguish.

bye,
//mirabilos
-- 
22:20⎜<asarch> The crazy that persists in his craziness becomes a master
22:21⎜<asarch> And the distance between the craziness and geniality is
only measured by the success 18:35⎜<asarch> "Psychotics are consistently
inconsistent. The essence of sanity is to be inconsistently inconsistent

**Comment by tomato42** [comment]
> Hubert Kario dixit:
>>  1. Actually if you are running Python 2, you're running some really Long Term Support distribution, like RHEL-6/CentOS 6, so those should be in minority; probably switching the python scripts to refer to python3 isn't a bad idea (possibly with a note for how to use `python2`).
>
> I’m not running Python 2 ;-) 
>
> ***@***.***:~ $ python
> /bin/mksh: python: inaccessible or not found
>
> I’m running py3k but it must be called as “python3”.

I meant hypothetically, if *anybody* is running python2 (or rather has to run python2), they're already are on an old distribution, so they should be in minority: as such we don't need to 

>> 2. I'm not sure about usefulness of a run-in-repo wrapper; if you're installing dependencies anyway, you might as well just install the repo itself...
>
> No, I’m installing the dependencies via the package manager. I’m an absolute enemy of constructs like pip, npm etc. so I’m not going to use them. All dependencies are available as proper Debian packages, so I’m not going to install *anything*, so a run-from-repo wrapper would be the standard way to go.

While I generally recommend to do that for the system-wide packages, you can also install python packages for the current user only, or even better, into a virtual environment. You still do that with pip.

>> 3. `parallel` needs to be the GNU one, yes. But I see that there is a note in README already that says that, not sure what we could do more to make it clear. It's not an action that regular users need to perform... (90% the reason it's there, is so that I remember what command to use to verify the primality certificates before I merge them)
>
> OK. But I apparently found an equivalent invocation for moreutils parallel. Maybe you can just include both, so the user will know? “man parallel” for moreutils starts with… PARALLEL(1) moreutils PARALLEL(1) … so this is how the user can distinguish. 

man pages may not be installed, using `parallel --version` should be more reliable

**Comment by mirabilos** [comment]
Hubert Kario dixit:

>I meant hypothetically, if *anybody* is running python2 (or rather has
>to run python2), they're already are on an old distribution, so they
>should be in minority: as such we don't need to

Yes, but that’s not the problem here. The problem is that the script
begins with #!/usr/bin/python instead of #!/usr/bin/python3 which
would be more correct.

>While I generally recommend to do that for the system-wide packages,
>you can also install python packages for the current user only, or even
>better, into a virtual environment. You still do that with pip.

That’s very dirty and leads to problems. I strongly recommend to never
do that or at least do it on throw-away separare user accounts only.

And anyway, the ecpp-verifier doesn’t _need_ to be installed.

>>> 3. `parallel` needs to be the GNU one, yes. But I see that there is
>>> a note in README already that says that, not sure what we could do
>>> more to make it clear. It's not an action that regular users need to
>>> perform... (90% the reason it's there, is so that I remember what
>>> command to use to verify the primality certificates before I merge
>>> them)
>>
>> OK. But I apparently found an equivalent invocation for moreutils
>> parallel. Maybe you can just include both, so the user will know?
>> “man parallel” for moreutils starts with… PARALLEL(1) moreutils
>> PARALLEL(1) … so this is how the user can distinguish.
>
>man pages may not be installed, using `parallel --version` should be
>more reliable

Manpages are always installed alongside the package, though yes,
man-db might be missing.

$ parallel --version; echo $?
parallel: invalid option -- '-'
parallel [OPTIONS] command -- arguments
        for each argument, run command with argument, in parallel
parallel [OPTIONS] -- commands
        run specified commands in parallel
1

This is not a good test. Maybe:

GNUparallel$ parallel echo ::: -- test
--
test

… versus…

moreutils$ parallel echo ::: -- test
::: test

**Comment by tomato42** [comment]
changed the `#!` to python3: #49
